#!/bin/sh

### BEGIN INIT INFO
# Provides:          autologin
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     5
# Default-Stop:      0 1 6
# Short-Description: Start for autlogin for joomla
# Description:       joomla.org
### END INIT INFO
# Author: <yves@compojoom.com>

# Aktionen
case "$1" in
    start)
        exec /sbin/agetty --autologin vagrant --noclear $1
        ;;
    stop)
        echo "Not implemented"
        ;;
    restart)
        echo "Not implemented"
        ;;
esac

exit 0
